# Generated by Django 2.1.7 on 2019-03-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190311_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closeTime',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='openTime',
            field=models.IntegerField(default=8),
        ),
    ]
