# Generated by Django 2.1.7 on 2019-03-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190311_0212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='guest', max_length=25, primary_key=True, serialize=False),
        ),
    ]
